/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Controlador.ControladorActas;
import Controlador.ControladorCandidatos;
import Controlador.ControladorElecciones;
import Controlador.ControladorMesas;
import Controlador.ControladorMiembros;
import Controlador.ControladorPartPoliticos;
import Controlador.ControladorRegistroVotos;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    ControladorPartPoliticos controladorPartido;
    ControladorCandidatos controladorCandidato;
    ControladorMiembros controladorMiembro;
    ControladorElecciones controladorEleccion;
    ControladorMesas controladorMesa;
    ControladorActas controladorActa;
    ControladorRegistroVotos controladorRegistroVoto;
    public Menu() {
        initComponents();
        controladorPartido = new ControladorPartPoliticos();
        controladorCandidato = new ControladorCandidatos();
        controladorMiembro = new ControladorMiembros();
        controladorEleccion = new ControladorElecciones();
        controladorMesa = new ControladorMesas();
        controladorActa = new ControladorActas();
        controladorRegistroVoto = new ControladorRegistroVotos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistros = new javax.swing.JMenu();
        menuPartidoPolitico = new javax.swing.JMenuItem();
        menuEleccion = new javax.swing.JMenuItem();
        menuCandidatos = new javax.swing.JMenuItem();
        menuMiembros = new javax.swing.JMenuItem();
        menuCandidatoEleccion = new javax.swing.JMenuItem();
        menuMesas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuActa = new javax.swing.JMenuItem();
        menuRegistroVoto = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuInforme = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU PRINCIPAL");

        menuRegistros.setText("Registros");

        menuPartidoPolitico.setText("Partido politico");
        menuPartidoPolitico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPartidoPoliticoActionPerformed(evt);
            }
        });
        menuRegistros.add(menuPartidoPolitico);

        menuEleccion.setText("Eleccion");
        menuEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEleccionActionPerformed(evt);
            }
        });
        menuRegistros.add(menuEleccion);

        menuCandidatos.setText("Candidatos");
        menuCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCandidatosActionPerformed(evt);
            }
        });
        menuRegistros.add(menuCandidatos);

        menuMiembros.setText("Miembros de mesa");
        menuMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMiembrosActionPerformed(evt);
            }
        });
        menuRegistros.add(menuMiembros);

        menuCandidatoEleccion.setText("Candidato a eleccion");
        menuCandidatoEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCandidatoEleccionActionPerformed(evt);
            }
        });
        menuRegistros.add(menuCandidatoEleccion);

        menuMesas.setText("Mesas electorales");
        menuMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMesasActionPerformed(evt);
            }
        });
        menuRegistros.add(menuMesas);

        jMenuBar1.add(menuRegistros);

        jMenu2.setText("Actas");

        menuActa.setText("Registrar acta electoral");
        menuActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActaActionPerformed(evt);
            }
        });
        jMenu2.add(menuActa);

        menuRegistroVoto.setText("Registrar votos en acta");
        menuRegistroVoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistroVotoActionPerformed(evt);
            }
        });
        jMenu2.add(menuRegistroVoto);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Informe");

        menuInforme.setText("Informe general");
        menuInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInformeActionPerformed(evt);
            }
        });
        jMenu1.add(menuInforme);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPartidoPoliticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPartidoPoliticoActionPerformed
        // TODO add your handling code here:
        RegistroPartPolitico ventana = new RegistroPartPolitico(controladorPartido);
        ventana.setVisible(true);
    }//GEN-LAST:event_menuPartidoPoliticoActionPerformed

    private void menuCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCandidatosActionPerformed
        // TODO add your handling code here:
        RegistroCandidato ventana = new RegistroCandidato(controladorCandidato, controladorPartido);
        ventana.setVisible(true);
    }//GEN-LAST:event_menuCandidatosActionPerformed

    private void menuMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMiembrosActionPerformed
        // TODO add your handling code here:
        RegistroMiembroMesa ventana = new RegistroMiembroMesa(controladorMiembro);
        ventana.setVisible(true);
    }//GEN-LAST:event_menuMiembrosActionPerformed

    private void menuEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEleccionActionPerformed
        // TODO add your handling code here:
        Elecciones ventana = new Elecciones(controladorEleccion);
        ventana.setVisible(true);
    }//GEN-LAST:event_menuEleccionActionPerformed

    private void menuCandidatoEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCandidatoEleccionActionPerformed
        // TODO add your handling code here:
        RegistroCandidatoEleccion ventana = new RegistroCandidatoEleccion(controladorEleccion, controladorCandidato);
        ventana.setVisible(true);
    }//GEN-LAST:event_menuCandidatoEleccionActionPerformed

    private void menuMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMesasActionPerformed
        // TODO add your handling code here:
        Mesas ventana = new Mesas(controladorMesa, controladorMiembro, controladorEleccion);
        ventana.setVisible(true);
               
    }//GEN-LAST:event_menuMesasActionPerformed

    private void menuActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActaActionPerformed
        // TODO add your handling code here:
        Actas ventana = new Actas(controladorActa, controladorMesa, controladorEleccion);
        ventana.setVisible(true);
    }//GEN-LAST:event_menuActaActionPerformed

    private void menuRegistroVotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistroVotoActionPerformed
        // TODO add your handling code here:
        RegistroVotos ventana = new RegistroVotos(controladorRegistroVoto,controladorActa,controladorCandidato);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_menuRegistroVotoActionPerformed

    private void menuInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInformeActionPerformed
        // TODO add your handling code here:
        InformeGeneral ventana = new InformeGeneral(controladorEleccion,controladorRegistroVoto);
        ventana.setVisible(true);
    }//GEN-LAST:event_menuInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem menuActa;
    private javax.swing.JMenuItem menuCandidatoEleccion;
    private javax.swing.JMenuItem menuCandidatos;
    private javax.swing.JMenuItem menuEleccion;
    private javax.swing.JMenuItem menuInforme;
    private javax.swing.JMenuItem menuMesas;
    private javax.swing.JMenuItem menuMiembros;
    private javax.swing.JMenuItem menuPartidoPolitico;
    private javax.swing.JMenuItem menuRegistroVoto;
    private javax.swing.JMenu menuRegistros;
    // End of variables declaration//GEN-END:variables
}
