/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Controlador.ControladorActas;
import Controlador.ControladorCandidatos;
import Controlador.ControladorRegistroVotos;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoprograobj.ActaElectoral;
import proyectoprograobj.Candidato;
import proyectoprograobj.RegistroVoto;

/**
 *
 * @author Usuario
 */
public class RegistroVotos extends javax.swing.JFrame {
    private DefaultComboBoxModel<String> modeloComboCandidatos;
    private DefaultComboBoxModel<String> modeloComboNumActa;
    private ControladorCandidatos controladorCandidato;
    private ControladorActas controladorActa;
    private ControladorRegistroVotos controlador;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroVotos.class.getName());

    /**
     * Creates new form RegistroVotos
     */
    public RegistroVotos() {
        initComponents();
        controlador = new ControladorRegistroVotos();
        controladorCandidato = new ControladorCandidatos();
        controladorActa = new ControladorActas();
        inicializarTabla();
        llenarComboCandidatos();
        llenarComboNumActa();
    }
    
    public RegistroVotos(ControladorRegistroVotos controlador,ControladorActas controladorActa,ControladorCandidatos controladorCandidato){
        initComponents();
        this.controlador = controlador;
        this.controladorActa = controladorActa;
        this.controladorCandidato = controladorCandidato;
        inicializarTabla();
        llenarComboCandidatos();
        llenarComboNumActa();
    }
    
    public void limpiar(){
        this.sprNulos.setValue(0);
        this.sprBlancos.setValue(0);
        this.sprEfectivos.setValue(0);
        this.cbxNumeroActa.setSelectedIndex(0);
        this.cbxCandidato.setSelectedIndex(0);
               
    }
    
    private void llenarComboCandidatos(){
        modeloComboCandidatos = new DefaultComboBoxModel<>();
        this.cbxCandidato.setModel(modeloComboCandidatos);
        LinkedList<Candidato> lista = controladorCandidato.getListaCandidatos();
        for (Candidato candidato : lista) {
            modeloComboCandidatos.addElement(candidato.getNombre());
        }
    }
    
    private void llenarComboNumActa(){
        modeloComboNumActa = new DefaultComboBoxModel<>();
        this.cbxNumeroActa.setModel(modeloComboNumActa);
        LinkedList<ActaElectoral> lista = controladorActa.getListaActas();
        for (ActaElectoral acta : lista) {
            modeloComboNumActa.addElement(acta.getNumeroActa());
        }
    }
    
    DefaultTableModel modeloTabla;
    public void inicializarTabla(){
        modeloTabla = new DefaultTableModel();
        this.tblRegistroVotos.setModel(modeloTabla);
        modeloTabla.addColumn("Numero de acta");
        modeloTabla.addColumn("Candidato");
        modeloTabla.addColumn("Votos efectivos");
        modeloTabla.addColumn("Votos nulos");
        modeloTabla.addColumn("Votos blancos");
    }
    
    private void mostrarRegistrosVotosTabla() {
        inicializarTabla(); 
        LinkedList<RegistroVoto> lista = controlador.getListaRegistroVotos();

        for (RegistroVoto registrovoto : lista) {
            String[] fila = new String[5];
            fila[0] = registrovoto.getActa().getNumeroActa();
            fila[1] = registrovoto.getCandidato().getNombre();
            fila[2] = String.valueOf(registrovoto.getVotosValidos());
            fila[3] = String.valueOf(registrovoto.getVotosNulos());
            fila[4] = String.valueOf(registrovoto.getVotosBlancos());

            modeloTabla.addRow(fila);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxNumeroActa = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxCandidato = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtVEfectivo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistroVotos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        sprEfectivos = new javax.swing.JSpinner();
        sprNulos = new javax.swing.JSpinner();
        sprBlancos = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar votos");

        jLabel2.setText("Numero de acta:");

        jLabel3.setText("Candidato:");

        jLabel4.setText("Votos a efectivos:");

        jLabel5.setText("Votos nulos:");

        jLabel6.setText("Votos en blanco:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tblRegistroVotos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegistroVotos);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        sprEfectivos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999999, 1));

        sprNulos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999999, 1));

        sprBlancos.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999999, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(48, 48, 48)
                                                .addComponent(cbxCandidato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbxNumeroActa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(133, 133, 133)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1)))
                                .addGap(100, 100, 100))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sprEfectivos, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                            .addComponent(sprNulos)
                                            .addComponent(sprBlancos))
                                        .addGap(240, 240, 240))
                                    .addComponent(jScrollPane1))
                                .addGap(97, 97, 97)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(txtVEfectivo)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxNumeroActa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sprEfectivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar))
                .addGap(26, 26, 26)
                .addComponent(btnCancelar)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sprNulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sprBlancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtVEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String nombreCandidato = this.cbxCandidato.getSelectedItem().toString();
        Candidato candidato = controladorCandidato.buscarCandidatoPorNombre(nombreCandidato);
        String numeroActa = this.cbxNumeroActa.getSelectedItem().toString();
        
        ActaElectoral acta = controladorActa.buscarActaPorNumActa(numeroActa);
        int votosEfectivos = (Integer)sprEfectivos.getValue();
        int votosBlancos = (Integer)sprBlancos.getValue();
        int votosNulos = (Integer)sprNulos.getValue();
        
        RegistroVoto registro = new RegistroVoto(acta,candidato,votosEfectivos,votosNulos,votosBlancos);
        boolean resultado = controlador.agregarRegistroVoto(registro);
        if (resultado) {
            JOptionPane.showMessageDialog(this, "Registro agregado correctamente.", "", JOptionPane.INFORMATION_MESSAGE);
            mostrarRegistrosVotosTabla(); // Mostrar los datos al instante
            limpiar(); // Limpiar los campos
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar el registro.", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String numeroActa = cbxNumeroActa.getSelectedItem().toString();
        String nombreCandidato = cbxCandidato.getSelectedItem().toString();

        boolean resultado = controlador.eliminarRegistroPorActaYCandidato(numeroActa, nombreCandidato);
        if (resultado) {
            JOptionPane.showMessageDialog(this, "Se elimino correctamente la informacion", "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error en el proceso de eliminacion.", "", JOptionPane.ERROR_MESSAGE);
        }

        limpiar();
        mostrarRegistrosVotosTabla();
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroVotos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbxCandidato;
    private javax.swing.JComboBox<String> cbxNumeroActa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner sprBlancos;
    private javax.swing.JSpinner sprEfectivos;
    private javax.swing.JSpinner sprNulos;
    private javax.swing.JTable tblRegistroVotos;
    private javax.swing.JTextField txtVEfectivo;
    // End of variables declaration//GEN-END:variables
}
